
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2019-2022 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.4.165.1")]
[assembly: AssemblyFileVersion("0.4.165.1")]
[assembly: AssemblyCompany("MANGOSLAB Co.,Ltd.")]
[assembly: AssemblyProduct("MANGOSLABCoLtd.RichTextKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2023, 4, 27, 16, 43, 24, DateTimeKind.Utc);
}
	