variables:
- template: DefaultVariableGroup.yml

- name: releaseState
  value: final

trigger: 
  batch: false
  tags:
    include:
    - v*.*.*

pr: none

resources:
  repositories:
    - repository: Mangoslab.Pipeline
      type: github
      name: MANGOSLABCoLtd/Mangoslab.Pipeline
      ref: refs/tags/v4.4.0
      endpoint: MANGOSLABCoLtd

stages:
- template: Stage/PublishTestResults.yml@Mangoslab.Pipeline
  parameters:
    checkoutSubmodules: ${{variables.checkoutSubmodules}}
    nugetConfigPath: ${{variables.nugetConfigPath}}
    minimumCodeCoverage: ${{variables.minimumCodeCoverage}}

- template: Stage/PublishNuGet.yml@Mangoslab.Pipeline
  parameters:
    checkoutSubmodules: ${{variables.checkoutSubmodules}}
    semanticVersion: ${{variables.semanticVersion}}
    releaseState: ${{variables.releaseState}}
    nugetConfigPath: ${{variables.nugetConfigPath}}
#    codeSigningCertHash: $(mangoslab-com)
    codeSigningCertPassword: $(codeSigningCertificatePassword)
