variables:
- template: DefaultVariableGroup.yml

- name: releaseState
  value: rc

trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
    exclude:
    - develop
    - feature/*
    - fix/*

resources:
  repositories:
    - repository: Mangoslab.Pipeline
      type: github
      name: MANGOSLABCoLtd/Mangoslab.Pipeline
      ref: refs/tags/v4.4.0
      endpoint: MANGOSLABCoLtd

stages:
- template: Stage/PublishTestResults.yml@Mangoslab.Pipeline
  parameters:
    checkoutSubmodules: ${{variables.checkoutSubmodules}}
    nugetConfigPath: ${{variables.nugetConfigPath}}
    minimumCodeCoverage: ${{variables.minimumCodeCoverage}}

- template: Stage/PublishNuGet.yml@Mangoslab.Pipeline
  parameters:
    checkoutSubmodules: ${{variables.checkoutSubmodules}}
    semanticVersion: ${{variables.semanticVersion}}
    nugetConfigPath: ${{variables.nugetConfigPath}}
    releaseState: ${{variables.releaseState}}
    #codeSigningCertHash: $(mangoslab-com)
    codeSigningCertPassword: $(codeSigningCertificatePassword)
